# 02 Cleaning

In [4]:
# Loading of the Dataset
import pandas as pd

df = pd.read_csv('../data/raw/vehicles_raw.csv')

print("Shape:", df.shape)
print(df.columns)

Shape: (48471, 26)
Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='str')

In [5]:
# Top 5 rows
df.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [6]:
# Last 5 rows
df.tail()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
48466,7305718110,https://wyoming.craigslist.org/cto/d/thermopol...,wyoming,https://wyoming.craigslist.org,6500,2002,ford,f 350,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00404_8EkKcC6XuW...,2002 Ford f 350 ext cab 295000 miles Power st...,NaN,wy,43.72509,-108.471457,2021-04-12T11:26:07-0600
48467,7305596553,https://wyoming.craigslist.org/cto/d/cheyenne-...,wyoming,https://wyoming.craigslist.org,2800,2000,chevrolet,s10 pickup,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00j0j_3i2W0MmbkI...,2000 Chevy S 10 pick up runs great 142000 mile...,NaN,wy,41.1084,-104.8107,2021-04-12T08:24:13-0600
48468,7305590558,https://wyoming.craigslist.org/cto/d/rawlins-2...,wyoming,https://wyoming.craigslist.org,9000,2015,jeep,wrangler unlimited,salvage,6 cylinders,...,NaN,SUV,black,https://images.craigslist.org/00909_iyoc54RPpy...,Salvage title from previous owner Engine damag...,NaN,wy,41.888456,-107.495083,2021-04-12T08:13:21-0600
48469,7305379796,https://wyoming.craigslist.org/cto/d/arapahoe-...,wyoming,https://wyoming.craigslist.org,6500,2011,subaru,forester,good,4 cylinders,...,NaN,NaN,NaN,https://images.craigslist.org/00g0g_lUE50arLcV...,This vehicle is in great shape! It's mechanica...,NaN,wy,42.9208,-108.5913,2021-04-11T16:25:00-0600
48470,7303806527,https://wyoming.craigslist.org/cto/d/laramie-2...,wyoming,https://wyoming.craigslist.org,800,2000,cadillac,deville,excellent,8 cylinders,...,full-size,coupe,white,https://images.craigslist.org/00f0f_1kOqCs4Ddv...,2000 Cadillac Deville Needs thermostats New ti...,NaN,wy,41.439,-105.801,2021-04-08T13:26:14-0600

In [7]:
# Null values and its counts
df.isnull().sum()

id                  0
url              9884
region           6901
region_url       6533
price            6446
year             6752
manufacturer    13723
model           13377
condition       22166
cylinders       24223
fuel            13650
odometer        13694
title_status    13669
transmission    13669
VIN             42214
drive           26506
size            32096
type            28159
paint_color     26257
image_url       13731
description     13733
county          47900
state           14062
lat             14186
long            14350
posting_date    14296
dtype: int64

In [8]:
# Duplicate removals
df = df.drop_duplicates(subset=['id'], keep='first')

In [9]:
# Cleaning cylinders column and formatting
# Extracting numeric values
df['cylinders'] = df['cylinders'].str.extract(r'(\d+)')
df['cylinders'] = pd.to_numeric(df['cylinders'], errors='coerce')

In [10]:
# Converting to numeric columns
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['year'] = pd.to_numeric(df['year'], errors='coerce')
df['odometer'] = pd.to_numeric(df['odometer'], errors='coerce')

In [11]:
# Handling numeric missing columns

# Drop rows where target variable is missing
df = df.dropna(subset=['price'])

# Fill important numeric features
df['year'] = df['year'].fillna(df['year'].median())
df['odometer'] = df['odometer'].fillna(df['odometer'].median())
df['cylinders'] = df['cylinders'].fillna(df['cylinders'].mode()[0])

# Drop unused geo columns
df = df.drop(columns=['lat', 'long'])

In [12]:
# Dropping irrelavant columns
df = df.drop(columns=[
    'url', 'region_url', 'image_url',
    'county', 'VIN'
], errors='ignore')

In [13]:
# Handling categorical missing values

# Droping weak / redundant columns
df = df.drop(columns=['region', 'size'], errors='ignore')


# Paint color → keep but avoid bias
df['paint_color'] = df['paint_color'].fillna('unknown')

# TEMP fill model for grouping only
df['model'] = df['model'].fillna('unknown_temp')

# -------------------------------
# Smart Imputation (BEFORE unknown fill)
# -------------------------------

# Fuel
fuel_map = df.groupby('model')['fuel'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
df['fuel'] = df['fuel'].fillna(df['model'].map(fuel_map))
df['fuel'] = df['fuel'].fillna(df['fuel'].mode()[0])

# Transmission
trans_map = df.groupby('model')['transmission'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
df['transmission'] = df['transmission'].fillna(df['model'].map(trans_map))
df['transmission'] = df['transmission'].fillna(df['transmission'].mode()[0])

# Type
type_map = df.groupby('model')['type'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
df['type'] = df['type'].fillna(df['model'].map(type_map))
df['type'] = df['type'].fillna(df['type'].mode()[0])

# Drive (model → type → fallback)
drive_map_model = df.groupby('model')['drive'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
df['drive'] = df['drive'].fillna(df['model'].map(drive_map_model))

drive_map_type = df.groupby('type')['drive'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
df['drive'] = df['drive'].fillna(df['type'].map(drive_map_type))

df['drive'] = df['drive'].fillna(df['drive'].mode()[0])


# Identity columns
df['manufacturer'] = df['manufacturer'].fillna('unknown')
df['model'] = df['model'].fillna('unknown')


# Independent columns
df['condition'] = df['condition'].fillna(df['condition'].mode()[0])
df['title_status'] = df['title_status'].fillna(df['title_status'].mode()[0])
df['state'] = df['state'].fillna(df['state'].mode()[0])
df['model'] = df['model'].replace('unknown_temp', 'unknown')

In [14]:
# Since we arent using text NLP dropping text column
df = df.drop(columns=['description'], errors='ignore')

In [15]:
# Outlier handling

# Price filtering
df = df[df['price'] >= 1500]
upper_price = df['price'].quantile(0.99)
df = df[df['price'] <= upper_price]


# Year filtering
max_year = df['year'].max()
df = df[(df['year'] >= 1980) & (df['year'] <= max_year)]


# Odometer filtering (refined)
lower_odo = max(500, df['odometer'].quantile(0.01))
upper_odo = df['odometer'].quantile(0.99)

df = df[(df['odometer'] >= lower_odo) & (df['odometer'] <= upper_odo)]


# Cylinders validation
df = df[df['cylinders'].isin([3, 4, 5, 6, 8, 10, 12])]

In [16]:
# Convert to datetime (force conversion)
df['posting_date'] = pd.to_datetime(df['posting_date'], errors='coerce', utc=True)

# NOW extract features
df['post_year'] = df['posting_date'].dt.year
df['post_month'] = df['posting_date'].dt.month

# Optional: drop rows where date is missing
df = df.dropna(subset=['post_year', 'post_month'])

# Drop original column
df = df.drop(columns=['posting_date'])

In [17]:
print("Final Shape:", df.shape)

print("\nNull Values:\n", df.isnull().sum())

print("\nSummary:\n", df.describe())

Final Shape: (27987, 17)

Null Values:
 id              0
price           0
year            0
manufacturer    0
model           0
condition       0
cylinders       0
fuel            0
odometer        0
title_status    0
transmission    0
drive           0
type            0
paint_color     0
state           0
post_year       0
post_month      0
dtype: int64

Summary:
               price          year     cylinders       odometer  post_year  \
count  27987.000000  27987.000000  27987.000000   27987.000000    27987.0
mean    9678.966127   2007.633866      5.847036  133963.895094     2021.0
std     8909.490567      6.791268      1.349175   59039.550952        0.0
min     1500.000000   1980.000000      3.000000     500.000000     2021.0
25%     4000.000000   2004.000000      4.000000   95633.000000     2021.0
50%     6750.000000   2008.000000      6.000000  133178.000000     2021.0
75%    11800.000000   2013.000000      6.000000  171135.000000     2021.0
max    56500.000000   2022.000000     12.000000  350962.000000     2021.0

         post_month
count  27987.000000
mean       4.341909
std        0.474358
min        4.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        5.000000

# Feature Engineering

In [18]:
# Using age instead of raw year for car age
current_year = df['post_year'].max()
df['car_age'] = current_year - df['year']

In [19]:
# Raw price is hard to interpret visually added cateogy column
def price_bucket(x):
    if x < 5000:
        return 'Budget'
    elif x < 15000:
        return 'Mid-range'
    else:
        return 'Premium'

df['price_category'] = df['price'].apply(price_bucket)

In [20]:
# Mileage Category
def mileage_bucket(x):
    if x < 50000:
        return 'Low'
    elif x < 150000:
        return 'Medium'
    else:
        return 'High'

df['mileage_category'] = df['odometer'].apply(mileage_bucket)

In [21]:
# Age category
def age_bucket(x):
    if x <= 3:
        return 'New'
    elif x <= 10:
        return 'Moderate'
    else:
        return 'Old'

df['age_category'] = df['car_age'].apply(age_bucket)

In [22]:
# Manufacturing Groups
# Too many brands → messy charts
top_brands = df['manufacturer'].value_counts().nlargest(10).index

df['manufacturer_grouped'] = df['manufacturer'].apply(
    lambda x: x if x in top_brands else 'other'
)

In [23]:
# Can identify Posting Season using months extracted previously
def get_season(month):
    if month in [12,1,2]:
        return 'Winter'
    elif month in [3,4,5]:
        return 'Spring'
    elif month in [6,7,8]:
        return 'Summer'
    else:
        return 'Fall'

df['posting_season'] = df['post_month'].apply(get_season)

In [24]:
df.head()
df.columns

Index(['id', 'price', 'year', 'manufacturer', 'model', 'condition',
       'cylinders', 'fuel', 'odometer', 'title_status', 'transmission',
       'drive', 'type', 'paint_color', 'state', 'post_year', 'post_month',
       'car_age', 'price_category', 'mileage_category', 'age_category',
       'manufacturer_grouped', 'posting_season'],
      dtype='str')

In [25]:
df.shape

(27987, 23)

In [28]:
# Converting Float type column to int , initially due to missing values it changed to float.
cols_to_int = ['year','post_year','post_month','car_age','cylinders','odometer']

for col in cols_to_int:
    df[col] = df[col].round().astype(int)

In [31]:
df.to_csv('../data/processed/vehicles_cleaned1.csv', index=False)