In [32]:
import pandas as pd

In [33]:
df = pd.read_csv("vehicles_cleaned.csv")

In [34]:
df

,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,...,drive,type,paint_color,state,lat,long,posting_date,car_age,post_year,post_month
0,anchorage / mat-su,23975.0,2015,mercedes-benz,cla250 4matic awd,UNKNOWN,UNKNOWN,gas,53348.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,ak,61.573915,-149.399197,2021-04-20 20:06:12+00:00,11,2021,4
1,fayetteville,36500.0,1973,chevrolet,camaro z28,UNKNOWN,UNKNOWN,gas,22673.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,ar,36.043600,-94.253900,2021-04-12 16:07:20+00:00,53,2021,4
2,flagstaff / sedona,21495.0,2018,ford,mustang,good,UNKNOWN,gas,63210.0,clean,...,UNKNOWN,other,silver,az,35.189958,-111.666438,2021-04-17 21:00:28+00:00,8,2021,4
3,huntsville / decatur,31900.0,2016,gmc,sierra 3500,UNKNOWN,UNKNOWN,gas,140000.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,al,35.265997,-87.322254,2021-05-01 18:41:49+00:00,10,2021,5
4,prescott,39495.0,2020,ram,1500,like new,8,gas,33629.0,clean,...,rwd,truck,silver,az,34.586025,-112.318347,2021-04-28 03:34:00+00:00,6,2021,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13062,dothan,32990.0,2017,jeep,wrangler unlimited sport,good,6,gas,30041.0,clean,...,4wd,other,silver,al,31.230000,-85.400000,2021-05-02 17:11:16+00:00,9,2021,5
13063,auburn,34590.0,2016,chevrolet,silverado 1500 double,good,6,gas,29499.0,clean,...,4wd,pickup,silver,al,32.590000,-85.480000,2021-05-03 17:41:33+00:00,10,2021,5
13064,fresno / madera,23999.0,2007,toyota,fj cruiser,UNKNOWN,6,gas,113000.0,clean,...,4wd,SUV,grey,ca,38.614287,-121.270495,2021-04-22 19:03:39+00:00,19,2021,4
13065,fresno / madera,10995.0,2013,ford,fusion,excellent,4,hybrid,110155.0,clean,...,fwd,sedan,red,ca,38.611926,-121.423565,2021-04-22 22:37:20+00:00,13,2021,4
13066,birmingham,6980.0,2008,toyota,avalon,UNKNOWN,6,gas,158888.0,clean,...,fwd,sedan,silver,al,33.209789,-86.783493,2021-04-18 19:30:28+00:00,18,2021,4

## Exploratory Data Analysis

In [35]:
print('--- Head of DataFrame ---')
display(df.head())

--- Head of DataFrame ---

,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,...,drive,type,paint_color,state,lat,long,posting_date,car_age,post_year,post_month
0,anchorage / mat-su,23975.0,2015,mercedes-benz,cla250 4matic awd,UNKNOWN,UNKNOWN,gas,53348.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,ak,61.573915,-149.399197,2021-04-20 20:06:12+00:00,11,2021,4
1,fayetteville,36500.0,1973,chevrolet,camaro z28,UNKNOWN,UNKNOWN,gas,22673.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,ar,36.043600,-94.253900,2021-04-12 16:07:20+00:00,53,2021,4
2,flagstaff / sedona,21495.0,2018,ford,mustang,good,UNKNOWN,gas,63210.0,clean,...,UNKNOWN,other,silver,az,35.189958,-111.666438,2021-04-17 21:00:28+00:00,8,2021,4
3,huntsville / decatur,31900.0,2016,gmc,sierra 3500,UNKNOWN,UNKNOWN,gas,140000.0,clean,...,UNKNOWN,UNKNOWN,UNKNOWN,al,35.265997,-87.322254,2021-05-01 18:41:49+00:00,10,2021,5
4,prescott,39495.0,2020,ram,1500,like new,8,gas,33629.0,clean,...,rwd,truck,silver,az,34.586025,-112.318347,2021-04-28 03:34:00+00:00,6,2021,4

In [36]:
print('--- DataFrame Info ---')
print(df.info())

--- DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13067 entries, 0 to 13066
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        13067 non-null  object
 1   price         13067 non-null  float64
 2   year          13067 non-null  int64
 3   manufacturer  13067 non-null  object
 4   model         13067 non-null  object
 5   condition     13067 non-null  object
 6   cylinders     13067 non-null  object
 7   fuel          13067 non-null  object
 8   odometer      13067 non-null  float64
 9   title_status  13067 non-null  object
 10  transmission  13067 non-null  object
 11  drive         13067 non-null  object
 12  type          13067 non-null  object
 13  paint_color   13067 non-null  object
 14  state         13067 non-null  object
 15  lat           13067 non-null  float64
 16  long          13067 non-null  float64
 17  posting_date  13067 non-null  object
 18  car_age       13067 non-null  int64
 19  post_year     13067 non-null  int64
 20  post_month    13067 non-null  int64
dtypes: float64(4), int64(4), object(13)
memory usage: 2.1+ MB
None

In [37]:
print('--- Numerical Summary Statistics ---')
display(df.describe())

--- Numerical Summary Statistics ---

,price,year,odometer,lat,long,car_age,post_year,post_month
count,13067.000000,13067.000000,1.306700e+04,13067.000000,13067.000000,13067.000000,13067.0,13067.000000
mean,20952.789852,2011.417923,9.293295e+04,38.366569,-111.139847,14.582077,2021.0,4.263259
std,13003.886769,10.096567,1.949219e+05,9.398371,19.654027,10.096567,0.0,0.440418
min,1012.000000,1922.000000,0.000000e+00,-81.838232,-158.599600,5.000000,2021.0,4.000000
25%,9995.000000,2009.000000,3.271050e+04,33.440000,-119.861991,9.000000,2021.0,4.000000
50%,18957.000000,2014.000000,7.790000e+04,34.787100,-111.922155,12.000000,2021.0,4.000000
75%,29990.000000,2017.000000,1.270805e+05,38.401800,-92.970850,17.000000,2021.0,5.000000
max,59999.000000,2021.000000,1.000000e+07,64.993698,-74.281707,104.000000,2021.0,5.000000

In [38]:
print('--- Categorical Summary Statistics ---')
display(df.describe(include='object'))

--- Categorical Summary Statistics ---

,region,manufacturer,model,condition,cylinders,fuel,title_status,transmission,drive,type,paint_color,state,posting_date
count,13067,13067,13067,13067,13067,13067,13067,13067,13067,13067,13067,13067,13067
unique,30,38,3675,7,8,5,6,3,4,14,13,5,12823
top,tucson,ford,f-150,UNKNOWN,UNKNOWN,gas,clean,automatic,UNKNOWN,sedan,UNKNOWN,az,2021-04-14 17:59:08+00:00
freq,1428,2623,258,5118,5263,10813,12662,9949,3765,2662,3400,4037,4

### 2. Univariate Analysis of Key Features

In [39]:
import matplotlib.pyplot as plt
import seaborn as sns